<a href="https://colab.research.google.com/github/margarevalo/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical Lab Exam 1

In [30]:
import numpy as np
A = np.array ([[1,2,3],[4,5,6]])
print("A =", A)
print()
B = np.array ([[1,2],[3,4],[5,6]])
print("B =", B)
print()
C = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print("C =", C)
print()
D = np.array ([[1,2],[3,4]])
print("D =", D)
print()
print("Examples")
print()

dot = np.dot(A,B)
print("a. AB =", dot)
print()

sum = D+D
print("b. D + D =", sum)
print()


S = 2*C
print("c. 2C =", S)

A = [[1 2 3]
 [4 5 6]]

B = [[1 2]
 [3 4]
 [5 6]]

C = [[1 2 3]
 [4 5 6]
 [7 8 9]]

D = [[1 2]
 [3 4]]

Examples

a. AB = [[22 28]
 [49 64]]

b. D + D = [[2 4]
 [6 8]]

c. 2C = [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [33]:
import numpy as np
A = np.array([5,3,-1])

print('Size of array:', A.size)
print('Type of array:', type(A))
print('Shape of array:', A.shape)
print('Dimension of array:', A.ndim)

Size of array: 3
Type of array: <class 'numpy.ndarray'>
Shape of array: (3,)
Dimension of array: 1
