<a href="https://colab.research.google.com/github/margarevalo/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and Its Operations

In [15]:
import numpy as np
A = np.array ([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
print(A)
print("")
print(B)

[[-5  0]
 [ 4  1]]

[[ 6 -3]
 [ 2  3]]


In [13]:
#Sum
import numpy as np
A = np.array ([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
print(A+B)

[[ 1 -3]
 [ 6  4]]


In [12]:
#Difference1
import numpy as np
A = np.array ([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
print(B-A)


[[11 -3]
 [-2  2]]


In [14]:
#Difference2
import numpy as np
A = np.array ([[-5,0],[4,1]])
B = np.array ([[6,-3],[2,3]])
print(A-B)

[[-11   3]
 [  2  -2]]
